- name: "Backup of necessary file before patching of server."
  user: root
  #sudo: yes
  hosts: all
  tasks:
    - name: taking backup of fstab, kernel version, mounted disks, running services and ports
      shell: |
        /bin/mkdir /tmp/patch-on-$(date +%d-%m-%Y)
        /bin/cp /etc/fstab /tmp/patch-on-$(date +%d-%m-%Y)
        uname -a >> /tmp/patch-on-$(date +%d-%m-%Y)/uname
        df -h >> /tmp/patch-on-$(date +%d-%m-%Y)/mounted_disks
        chkconfig --list >> /tmp/patch-on-$(date +%d-%m-%Y)/running_services
        netstat -tunlp >> /tmp/patch-on-$(date +%d-%m-%Y)/listening_ports

    - name: Uptime of the machine
      shell: /usr/bin/uptime
      register: uptime

    - debug: var={{ item }}
      with_items:
        - uptime.stdout
    
